---
name: ROS2 test build

on:
  - push

jobs:
  colcon-test-build-jazzy:
    strategy:
      matrix:
        ros-distro: [jazzy]
    runs-on: ubuntu-24.04
    container:
      image: ros:${{ matrix.ros-distro }}-ros-core

    name: Build ${{ matrix.ros-distro }}
    steps:
      - run: apt-get update && apt-get install -y ros-dev-tools

      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: husarion_components_description
          target-ros2-distro: ${{ matrix.ros-distro }}

  colcon-test-build-humble:
    strategy:
      matrix:
        ros-distro: [humble]
    runs-on: ubuntu-22.04
    container:
      image: ros:${{ matrix.ros-distro }}-ros-core

    name: Build ${{ matrix.ros-distro }}
    steps:
      - run: apt-get update && apt-get install -y ros-dev-tools

      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: husarion_components_description
          target-ros2-distro: ${{ matrix.ros-distro }}
